## String operations

In [56]:
from __future__ import print_function
import numpy as np

In [57]:
np.__version__

'2.2.4'

Q1. Concatenate x1 and x2.

In [58]:
x1 = np.array(['Hello', 'Say'])
x2 = np.array([' world', ' something'])
np.char.add(x1,x2)

array(['Hello world', 'Say something'], dtype='<U15')

Q2. Repeat x three time element-wise.

In [59]:
x = np.array(['Hello ', 'Say '])
np.char.multiply(x, 3)

array(['Hello Hello Hello ', 'Say Say Say '], dtype='<U18')

Q3-1. Capitalize the first letter of x element-wise.<br/>
Q3-2. Lowercase x element-wise.<br/>
Q3-3. Uppercase x element-wise.<br/>
Q3-4. Swapcase x element-wise.<br/>
Q3-5. Title-case x element-wise.<br/>

In [60]:
x = np.array(['heLLo woRLd', 'Say sOmething'])
# CODE HERE

x1 = np.char.capitalize(x)
x2 = np.char.lower(x)
x3 = np.char.upper(x)
x4 = np.char.swapcase(x)
x5 = np.char.title(x)

print("capitalized =", x1)
print("lowercase =", x2)
print("uppercase =", x3)
print("swapcase =", x4)
print("title =", x4)

capitalized = ['Hello world' 'Say something']
lowercase = ['hello world' 'say something']
uppercase = ['HELLO WORLD' 'SAY SOMETHING']
swapcase = ['HEllO WOrlD' 'sAY SoMETHING']
title = ['HEllO WOrlD' 'sAY SoMETHING']


Q4. Make the length of each element 20 and the string centered / left-justified / right-justified with paddings of `_`.

In [61]:
x = np.array(['hello world', 'say something'])
# CODE HERE

x1 = np.char.center(x, 20, '_')
x2 = np.char.ljust(x, 20, '_')
x3 = np.char.rjust(x, 20, '_')

print("centered =", x1)
print("left-justified =", x2)
print("right-justified =", x3)

centered = ['____hello world_____' '___say something____']
left-justified = ['hello world_________' 'say something_______']
right-justified = ['_________hello world' '_______say something']


Q5. Encode x in cp500 and decode it again.

In [62]:
x = np.array(['hello world', 'say something'])
# CODE HERE

x_encode = np.char.encode(x, 'cp500')
x_decode = np.char.decode(x_encode, 'cp500')

print("encoded =", x_encode)
print("decoded =", x_decode)

encoded = [b'\x88\x85\x93\x93\x96@\xa6\x96\x99\x93\x84'
 b'\xa2\x81\xa8@\xa2\x96\x94\x85\xa3\x88\x89\x95\x87']
decoded = ['hello world' 'say something']


Q6. Insert a space between characters of x.

In [63]:
x = np.array(['hello world', 'say something'])
# CODE HERE

np.char.join(' ', x)

array(['h e l l o   w o r l d', 's a y   s o m e t h i n g'], dtype='<U25')

Q7-1. Remove the leading and trailing whitespaces of x element-wise.<br/>
Q7-2. Remove the leading whitespaces of x element-wise.<br/>
Q7-3. Remove the trailing whitespaces of x element-wise.

In [64]:
x = np.array(['   hello world   ', '\tsay something\n'])
# CODE HERE

x1 = np.char.strip(x)
x2 = np.char.lstrip(x)
x3 = np.char.rstrip(x)

print("stripped =", x1)
print("left stripped =", x2)
print("right stripped =", x3)

stripped = ['hello world' 'say something']
left stripped = ['hello world   ' 'say something\n']
right stripped = ['   hello world' '\tsay something']


Q8. Split the element of x with spaces.

In [65]:
x = np.array(['Hello my name is John'])
# CODE HERE

np.char.split(x, ' ').tolist()

[['Hello', 'my', 'name', 'is', 'John']]

Q9. Split the element of x to multiple lines.

In [66]:
x = np.array(['Hello\nmy name is John'])
# CODE HERE

np.char.splitlines(x).tolist()

[['Hello', 'my name is John']]

Q10. Make x a numeric string of 4 digits with zeros on its left.

In [ ]:
x = np.array(['34'])
# CODE HERE

left_fill = str(np.char.zfill(x, 4)) # left fill with 0
right_fill = str(np.char.ljust(x, 4, fillchar='0')) # right fill with 0

print("left fill =", left_fill)
print("right fill =", right_fill)

left fill = ['0034']
right fill = ['3400']


Q11. Replace "John" with "Jim" in x.

In [68]:
x = np.array(['Hello nmy name is John'])
# CODE HERE

np.char.replace(x, "John", "Jim")

array(['Hello nmy name is Jim'], dtype='<U21')

## Comparison

Q12. Return x1 == x2, element-wise.

In [69]:
x1 = np.array(['Hello', 'my', 'name', 'is', 'John'])
x2 = np.array(['Hello', 'my', 'name', 'is', 'Jim'])
# CODE HERE

x1 == x2

array([ True,  True,  True,  True, False])

Q13. Return x1 != x2, element-wise.

In [70]:
x1 = np.array(['Hello', 'my', 'name', 'is', 'John'])
x2 = np.array(['Hello', 'my', 'name', 'is', 'Jim'])
# CODE HERE

x1 != x2

array([False, False, False, False,  True])

## String information

Q14. Count the number of "l" in x, element-wise.

In [71]:
x = np.array(['Hello', 'my', 'name', 'is', 'Lily'])
# CODE HERE

np.char.count(x, 'l')

array([2, 0, 0, 0, 1])

Q15. Count the lowest index of "l" in x, element-wise.

In [72]:
x = np.array(['Hello', 'my', 'name', 'is', 'Lily'])
# CODE HERE

np.char.find(x, 'l')

array([ 2, -1, -1, -1,  2])

Q16-1. Check if each element of x is composed of digits only.<br/>
Q16-2. Check if each element of x is composed of lower case letters only.<br/>
Q16-3. Check if each element of x is composed of upper case letters only.

In [73]:
x = np.array(['Hello', 'I', 'am', '20', 'years', 'old'])
# CODE HERE

x1 = np.char.isdigit(x)
x2 = np.char.islower(x)
x3 = np.char.isupper(x)

print("Digit only =", x1)
print("Lower cases only =", x2)
print("Upper cases only =", x3)

Digit only = [False False False  True False False]
Lower cases only = [False False  True False  True  True]
Upper cases only = [False  True False False False False]


Q17. Check if each element of x starts with "hi".

In [74]:
x = np.array(['he', 'his', 'him', 'his'])
# CODE HERE

np.char.startswith(x, 'hi')

array([False,  True,  True,  True])